services:
  django-ninja-api:
    build:
      context: .
      args:
        - BASE_IMAGE_VERSION=${BASE_IMAGE_VERSION}
      dockerfile: ./docker/dockerfile
    container_name: ${PROJECT_NAME}-django-ninja-api
    image: ${PROJECT_NAME}-django-ninja-api:${BASE_IMAGE_VERSION}
    ports:
      - 8000:8000
    env_file:
      - ./envs/.env.local
    # volumes:
    #   - ./backend/django-ninja-api/django-ninja-api:/app
    depends_on:
      - pgsql
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py collectstatic && python main.py"

  pgsql:
    image: postgres:13
    container_name: ${PROJECT_NAME}-pgsql
    ports:
      - 5432:5432
    env_file:
      - ./envs/.env.local
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    restart: always

  redis:
    image: redis:6
    container_name: ${PROJECT_NAME}-redis
    restart: always
