FROM python:3.12.5-bullseye

# Basis
RUN apt-get update -y && \
    apt-get install -y build-essential libpq-dev

# Python
COPY requirements/base.txt base.txt
RUN pip install --upgrade pip
RUN pip install -r base.txt
