FROM python:3.12.5-bullseye

# Basis
RUN apt-get update -y
RUN apt-get install -y build-essential 
RUN apt-get install libpq5=13.4-1
RUN apt-get install -y libpq-dev

# Python
COPY ./requirements/base.txt ./requirements/base.txt
RUN pip install --upgrade pip
RUN pip install -r ./requirements/base.txt
